/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.GermplasmAttributeCategoriesResponse;
import io.swagger.model.GermplasmAttributeDefsResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-01T19:24:22.162Z")

@Api(value = "attributes", description = "the attributes API")
public interface AttributesApi {

    @ApiOperation(value = "Germplasm attribute categories", nickname = "attributesCategoriesGet", notes = " Scope: OTHER. Status: ACCEPTED. Implementation target date: PAG2016 List all available attribute categories. <a href=\"https://test-server.brapi.org/brapi/v1/attributes\"> test-server.brapi.org/brapi/v1/attributes/categories</a>", response = GermplasmAttributeCategoriesResponse.class, tags={ "Germplasm Attributes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = GermplasmAttributeCategoriesResponse.class) })
    @RequestMapping(value = "/attributes/categories",
        method = RequestMethod.GET)
    ResponseEntity<GermplasmAttributeCategoriesResponse> attributesCategoriesGet(@ApiParam(value = "The size of the pages to be returned. Default is `1000`.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.") @Valid @RequestParam(value = "page", required = false) Integer page);


    @ApiOperation(value = "Attributes by attributeCategoryDbId", nickname = "attributesGet", notes = " List available attributes. <a href=\"https://test-server.brapi.org/brapi/v1/attributes\"> test-server.brapi.org/brapi/v1/attributes</a> ", response = GermplasmAttributeDefsResponse.class, tags={ "Germplasm Attributes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = GermplasmAttributeDefsResponse.class) })
    @RequestMapping(value = "/attributes",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GermplasmAttributeDefsResponse> attributesGet(@ApiParam(value = "filter for kind of attributes") @Valid @RequestParam(value = "attributeCategoryDbId", required = false) String attributeCategoryDbId,@ApiParam(value = "The size of the pages to be returned. Default is `1000`.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.") @Valid @RequestParam(value = "page", required = false) Integer page);

}
