/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CommonCropNamesResponse;
import io.swagger.annotations.*;

import org.brapi.test.BrAPITestServer.exceptions.BrAPIServerException;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-04T21:50:05.517Z")

@Api(value = "crops", description = "the crops API")
public interface CropsApi {

    @ApiOperation(value = "List supported crops", nickname = "cropsGet", notes = "For multi crop systems this is a useful call to list all the supported crops.  <a href=\"https://test-server.brapi.org/brapi/v1/crops\"> test-server.brapi.org/brapi/v1/crops</a>", response = CommonCropNamesResponse.class, tags={ "Crops","Deprecated", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CommonCropNamesResponse.class) })
    @RequestMapping(value = "/crops",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CommonCropNamesResponse> cropsGet(@ApiParam(value = "The size of the pages to be returned. Default is `1000`.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.") @Valid @RequestParam(value = "page", required = false) Integer page) throws BrAPIServerException;

}
