/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ProgramsResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-01T19:24:22.162Z")

@Api(value = "programs", description = "the programs API")
public interface ProgramsApi {

    @ApiOperation(value = "List programs", nickname = "programsGet", notes = " Call to retrieve a list of programs. Status: ACCEPTED Implemented By: <a href=\"https://test-server.brapi.org/brapi/v1/programs\"> test-server.brapi.org/brapi/v1/programs</a>", response = ProgramsResponse.class, tags={ "Programs", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProgramsResponse.class) })
    @RequestMapping(value = "/programs",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ProgramsResponse> programsGet(@ApiParam(value = "Filter by program name. Exact match.") @Valid @RequestParam(value = "programName", required = false) String programName,@ApiParam(value = "Filter by program abbreviation. Exact match.") @Valid @RequestParam(value = "abbreviation", required = false) String abbreviation,@ApiParam(value = "The size of the pages to be returned. Default is `1000`.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.") @Valid @RequestParam(value = "page", required = false) Integer page);

}
