/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-04T21:50:05.517Z")

@Api(value = "token", description = "the token API")
public interface TokenApi {

    @ApiOperation(value = "Logout", nickname = "tokenDelete", notes = "", tags={ "Authentication","Deprecated", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created") })
    @RequestMapping(value = "/token",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> tokenDelete();


    @ApiOperation(value = "Login", nickname = "tokenPost", notes = "", tags={ "Authentication","Deprecated", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created") })
    @RequestMapping(value = "/token",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> tokenPost();

}
