/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;
import org.brapi.test.BrAPITestServer.exceptions.BrAPIServerException;

import io.swagger.model.ObservationVariableSearchRequestDep;
import io.swagger.model.ObservationVariablesResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-05T14:32:54.779-05:00[America/New_York]")

@Api(value = "variables-search", description = "the variables-search API")
public interface VariablesSearchApi {

    @ApiOperation(value = "Variable search", nickname = "variablesSearchPost", notes = "Search observation variables.  See Search Services for additional implementation details.", response = ObservationVariablesResponse.class, authorizations = {
        @Authorization(value = "AuthorizationToken")
    }, tags={ "Observation Variables", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ObservationVariablesResponse.class) })
    @RequestMapping(value = "/variables-search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ObservationVariablesResponse> variablesSearchPost(@ApiParam(value = ""  )  @Valid @RequestBody ObservationVariableSearchRequestDep body) throws BrAPIServerException;

}
